---
controller_projects:
  - name: "Controller Configuration"
    description: ""
    organization: "Default"
    scm_type: "git"
    scm_url: "https://github.com/tosmi-ansible/aap-setup.git"
    # scm_credential: "stderr.at GitLab AAP"
    scm_branch: "main"
    scm_clean: "False"
    scm_delete_on_update: "True"
    scm_update_on_launch: "False"
    scm_update_cache_timeout: "0"
    allow_override: "False"
    timeout: 0
...
